language: python
python:
- '3.5'
install:
- pip3 install -r requirements.txt
script:
- python3 test.py
deploy:
  provider: heroku
  api_key:
    secure: URGA2ytZzPhBffEfJWvMKqZ6wl5sDF+cy5MObIN9T86Ge53O61/wqqVPDEZG1Yzg/5R6kA6l3raewCX09B5w406fWDvS8/m0lE1o2vquY4T4k+Qq3MVbirNIusoGrBz7S3Z0dYOCki2UxbWxPJPl+3razzGEzH77XIQ5IKKnZt/xsbWBm8sWdhc4IYdN/8pOZhQBIn/Usoq+yUbzSuaHpXHTIZbzzsgPAIMoAHoZ+LCwEymmZeU10fqR9YvBrH3hVH9Gsk59QBJ8uxBf4GbM2/41S394hymNkWjPRbZj2lc97JB+P07I2jMV0es1HX9ebIWuRryoVmQFLO8YUWkQL6zxF1YZMa1KKMzK0uJpOp/MxqlZ9/HAXDZNczvla7Ze1K/O8EUOYVdzqe1gP4BGR2thDSfQbjpWqR7bsDuTeEtyfnmktReJioIaD8WYDNd6ISFopRTvXNz0AqgP/2Z7amgwsC3RXpPyxb+QXN5dTgVgRIpyYJrglfSs06N8uVLHA579PR5zp+PkTjpzxTVSwljycdDppS//F05db0huLwt8tfwSasxKpF06PQEiFeLvt4PvZ1t1QnomKzYDOhqMDkoIoKqQ1yeNbRtRnkAZP7EGLDrOppO8pkWNrnJyV15JudcPZNEQXm56k+FYHP8rfKcNfNjDBh95XGQZQMLoPno=
  app: arslan-jusivow