language: python
python:
- '3.5'
install:
- pip3 install -r requirements.txt
script:
- python3 test.py
deploy:
  provider: heroku
  api_key:
    secure: fSsuxUQElxaXDk4jfzDB8sM6jQ2YBN87MbvC7KXFME5nWmr4DTf6MhXZWaf1LgfXHDK7h4hZYdIF9MpG8POwhnfFieuTL2GzepeyjcJOXaQTwui5isITZmCLGc84JPctFWwwUOvhqned2IJXtYFV+An/v9XOWkzlCLJ53crqOX79vM8tZ4IhgqFcqdYvyuDvBTBgI/lROPFmX2Li+RefmPucnPkiNXstsOQ+jVTm2i92U+kgT487jIUryPWzPURMW2dAq6Agz1ZmRoRJQa6413b9LBet/5aklxjVV4OHbpaeygqjtD4b0byBLiB2gLzoGJNFfEund80U+DsjcXT94oXBrQo8RNwj89I6wmEtDJjrkzKmIZx5f3p9amcp4yPC5UGtXiwtnEWQkxo8zyfMYt67HG+lzpRJuEvO624Xui0TYeTvhKqVxiWeUOSIu10v3VGVSyTnhmd1c2lZY0+hILHCscND2WNnfw6rezSlifmycNejxNdhu5v2vLy2UTuU1sLcx2MXEiyZqPxKYifW1uSORuB5eRFhRviu8mA5RZCPhcKz4TJpvnlUUBE84C/5AXFlh2N41khPrDWndFvcC9jn9XNDrhusD3e1P8VIp8epRfAAlDSzPfqyYG/5Fq7TWJD4ZriIUE3psuipDb8rPKGAOqf4IXHruDAftR2Tunc=
  app: arslan-jusivow
