language: python
python:
- '3.5'
install:
- pip3 install -r requirements.txt
script:
- python3 test.py
deploy:
  provider: heroku
  api_key:
    secure: mlDo5Gxg3S1DToCL9f1IksmLji/8M6DBeFYYUY/ARkzWpr3mzKaQFtsvOoLNo1AQjsxiLjZjqTaajEdDOpiQ5SUos/Hr6n/BNDVoSyTZ+IRX5I++hB4q/upqiImr6XokVMZQZA9S6tsP+oEZ0m7gbzpPxWMAY5elGxXx0kxBKt6ptVAtgEc9YYbh+MViKm7WWxos640DhNSsVXVg/gqiSmQs10ypwnMQsT4g4ezhac4LuEsfNir0XvuCFnVqKu6cmQGo/EFc84434PlYY2F8G79Rvu7a80SaXAPst/FHfZNun/iS+eJw5zZMQEjfkBw8N0jwPTAVxZtbyc7torVT4OVZC1h6kNQ5TLWmrV6as6sZmSuRKdVEdCvcnlN8kMFM1fXtqvIi1v6DyqwAMfsaSnqE5UzYToZY0NuqV6plqCCer0hjt9O8YRQWHk5TimN7LAG+186MqkOq/LpYcnsBzP6CAA5GwK/cA2Bn98mjnjdI8yjD7o+6TAIO0lYVkXFhAtlt07PspAMqTEAZCwLmxCVFp1mMVgZuAjTIe5bbNBm4iTp7v+jphvM5ps8qhG+l4JedzHlX0Cg5TlSkyoMZyWupIKCi4yHmD2s6MuVKVfTWSSVrkHXgU9yMKg9NFaHRow4qo+UyPlQ7zrWCcXAnHUAwnrsOV7CG69QMo5ZZ+4w=
  app: arslan-jusivow
